### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by Wohlstand** [chrg127/libgsf#3]
Hello!

Looks like you didn't declared any license. That a problem. Your project by default can't be freely used by people because of the "all rights reserved". So, nobody can legally use your thing at all. Please add one of popular licenses (MIT, BSD3, ZLib, LGPL, etc.), or write your own to describe how people can use your library.

Also, if you ever had to use any component that is licensed under GPL, so, your license will be GPL by default.

P.S. I see, you do use the mGBA emulator as a dependency and I see it has the Mozilla Public License. So, you probably just add the same license to here.

**Comment by chrg127** [comment]
Hello, I've added a license now.
